data:
  name: 'ACIC2018'
  Ydim: 1

training:
  epochs: 150
  batch_size: 200

test:
  epochs: 10
  if_test_KL_metric: False # Notice that testing KL metric can be time-demanding
  KL_metric_epoch: 80
